<?php

namespace AppBundle\Repository;

/**
 * ClassifiedsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassifieldsRepository extends \Doctrine\ORM\EntityRepository
{
}
